/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary1: {
          DEFAULT: "hsl(var(--primary1))",
          foreground: "hsl(var(--primary1-foreground))",
          1: "hsl(var(--green1))",
          2: "hsl(var(--green2))",
          3: "hsl(var(--green3))",
          4: "hsl(var(--green4))",
          5: "hsl(var(--green5))",
          6: "hsl(var(--green6))",
          7: "hsl(var(--green7))",
          8: "hsl(var(--green8))",
          9: "hsl(var(--green9))",
          10: "hsl(var(--green10))",
        },
        primary2: {
          DEFAULT: "hsl(var(--primary2))",
          foreground: "hsl(var(--primary2-foreground))",
          1: "hsl(var(--light-blue1))",
          2: "hsl(var(--light-blue2))",
          3: "hsl(var(--light-blue3))",
          4: "hsl(var(--light-blue4))",
          5: "hsl(var(--light-blue5))",
          6: "hsl(var(--light-blue6))",
          7: "hsl(var(--light-blue7))",
          8: "hsl(var(--light-blue8))",
          9: "hsl(var(--light-blue9))",
          10: "hsl(var(--light-blue10))",
        },
        neutral: {
          DEFAULT: "hsl(var(--cool-gray5))",
          1: "hsl(var(--cool-gray1))",
          2: "hsl(var(--cool-gray2))",
          3: "hsl(var(--cool-gray3))",
          4: "hsl(var(--cool-gray4))",
          5: "hsl(var(--cool-gray5))",
          6: "hsl(var(--cool-gray6))",
          7: "hsl(var(--cool-gray7))",
          8: "hsl(var(--cool-gray8))",
          9: "hsl(var(--cool-gray9))",
          10: "hsl(var(--cool-gray10))",
        },
        purple: {
          1: "hsl(var(--purple1))",
          2: "hsl(var(--purple2))",
          3: "hsl(var(--purple3))",
          4: "hsl(var(--purple4))",
          5: "hsl(var(--purple5))",
          6: "hsl(var(--purple6))",
          7: "hsl(var(--purple7))",
          8: "hsl(var(--purple8))",
          9: "hsl(var(--purple9))",
          10: "hsl(var(--purple10))",
        },
        red: {
          1: "hsl(var(--red1))",
          2: "hsl(var(--red2))",
          3: "hsl(var(--red3))",
          4: "hsl(var(--red4))",
          5: "hsl(var(--red5))",
          6: "hsl(var(--red6))",
          7: "hsl(var(--red7))",
          8: "hsl(var(--red8))",
          9: "hsl(var(--red9))",
          10: "hsl(var(--red10))",
        },
        yellow: {
          1: "hsl(var(--yellow1))",
          2: "hsl(var(--yellow2))",
          3: "hsl(var(--yellow3))",
          4: "hsl(var(--yellow4))",
          5: "hsl(var(--yellow5))",
          6: "hsl(var(--yellow6))",
          7: "hsl(var(--yellow7))",
          8: "hsl(var(--yellow8))",
          9: "hsl(var(--yellow9))",
          10: "hsl(var(--yellow10))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
